# vim: ts=2 sw=2 et :
---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags:
    - rbenv

# Install packages
- name: install rbenv build dependencies
  package:
    name: "{{ rbenv_packages }}"
    state: "{{ rbenv_packages_state }}"
  when: rbenv_packages
  become: yes
  tags:
    - rbenv

- name: install rbenv sources
  git:
    repo: "{{ rbenv_source_repo }}"
    dest: "~/{{ rbenv_path }}"
    version: "{{ rbenv_source_version }}"
  become: no
  tags:
    - rbenv

# Set up configuration file
- name: create configuration files
  template:
    dest: "~/.{{ rbenv_conf_file }}"
    src: "{{ rbenv_conf_file }}"
    force: no
  become: no
  when: rbenv_conf_file is defined
  tags:
    - "rbenv"
    - "rbenv_conf"

- name: configure rbenv path
  lineinfile:
    dest: "~/.{{ rbenv_conf_file }}"
    line: '[[ -d ~/{{ rbenv_bin_path }} ]] && export PATH="~/{{ rbenv_bin_path }}:$PATH"'
  become: no
  tags:
    - "rbenv"
    - "rbenv_conf"

- name: rbenv init
  lineinfile:
    dest: "~/.{{ rbenv_conf_file }}"
    line: "[[ -f ~/{{ rbenv_bin_path }}/rbenv ]] && eval \"$(~/{{ rbenv_bin_path }}/rbenv init -)\""
  become: no
  tags:
    - "rbenv"
    - "rbenv_conf"

- name: rbenv plugin directory
  file:
    dest: "~/{{ rbenv_plugin_path }}"
    state: directory
  become: no
  tags:
    - "rbenv"
    - "rbenv_conf"

- name: rbenv plugins
  git:
    repo: "{{ item['repo'] }}"
    dest: "~/{{ rbenv_plugin_path }}/{{ item['name'] }}"
    version: "{{ item['version'] | default('master') }}"
  become: no
  with_items:
    - "{{ rbenv_plugins }}"
  tags:
    - "rbenv"
    - "rbenv_conf"

- name: rbenv install ruby version
  shell: "~/{{ rbenv_bin_path }}/rbenv install $(echo {{ item }})"
  args:
    creates: "~/{{ rbenv_path }}/versions/{{ item }}"
  with_items:
    - "{{ rbenv_ruby_versions }}"
