# vim: ts=2 sw=2 et :
---
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags:
    - rbenv

- name: install rbenv dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ rbenv_packages }}"
  tags:
    - rbenv

- name: install rbenv sources
  become: no
  git:
    repo: "{{ rbenv.repo }}"
    dest: "{{ rbenv.path }}"
    version: "{{ rbenv.version }}"
  tags:
    - rbenv

- name: create configuration files
  become: no
  template:
    dest: "{{ _rbenv.conf }}"
    src: bash_profile
    force: no
  vars:
    path:
      bin: "{{ _rbenv.path.bin }}"
  tags:
    - "rbenv"

- name: configure rbenv path
  become: no
  lineinfile:
    dest: "{{ _rbenv.conf }}"
    line: '[[ -d {{ _rbenv.path.bin }} ]] && export PATH="{{ _rbenv.path.bin }}:$PATH"'
  tags:
    - "rbenv"

- name: rbenv init
  become: no
  lineinfile:
    dest: "{{ _rbenv.conf }}"
    line: "[[ -f {{ _rbenv.path.bin }}/rbenv ]] && eval \"$({{ _rbenv.path.bin }}/rbenv init -)\""
  tags:
    - "rbenv"

- name: rbenv plugin directory
  become: no
  file:
    dest: "{{ _rbenv.path.plugins }}"
    state: directory
  tags:
    - "rbenv"

- name: rbenv plugins
  become: no
  git:
    repo: "{{ item['repo'] }}"
    dest: "{{ _rbenv.path.plugins }}/{{ item['name'] }}"
    version: "{{ item['version'] | default('master') }}"
  with_items:
    - "{{ rbenv.plugins }}"
  tags:
    - "rbenv"

- name: Set up default gems
  template:
    dest: "{{ rbenv.path }}/default-gems"
    src: list
  vars:
    items: "{{ rbenv.gems }}"
  tags:
    - "rbenv"

- name: rbenv install ruby version
  become: no
  command: "{{ _rbenv.path.bin }}/rbenv install {{ rbenv.ruby }}"
  args:
    creates: "{{ rbenv.path }}/versions/{{ rbenv.ruby }}"
  tags:
    - "rbenv"

- name: rbenv set default ruby
  become: no
  template:
    dest: "{{ rbenv.path }}/version"
    src: list
  vars:
    items:
      - 2.4.1
  tags:
    - "rbenv"
