---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: centos7
    image: centos:7
  - name: stretch
    image: debian:stretch
  - name: bionic
    image: ubuntu:bionic
  - name: xenial
    image: ubuntu:xenial
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        rbenv_bash_conf: yes
scenario:
  name: default
verifier:
  name: testinfra
