---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: debian
    image: debian:stretch
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian:
        rbenv_ruby: 2.4.1
        rbenv_gems:
          - sensu
        rbenv_ruby_path: /opt/ruby
scenario:
  name: compile
verifier:
  name: testinfra
