---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian
    image: debian:stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      debian:
        rbenv_ruby: 2.4.1
        rbenv_gems: sensu
        rbenv_user: rbenv
scenario:
  name: compile
verifier:
  name: testinfra
  lint:
    name: flake8
