---
- name: Converge
  hosts: all
  tasks:
    - name: create required users
      user:
        name: rbenv
        group: users
        shell: /bin/bash
        home: /opt/rbenv
        system: yes
    - name: apply test role
      include_role:
        name: nephelaiio.rbenv
