---
- name: Converge
  hosts: all
  tasks:
    - user:
        name: rbenv
        group: users
        shell: /bin/bash
        home: /opt/rbenv
        system: yes
    - include_role:
        name: nephelaiio.rbenv
